spring:
    datasource:
      url: jdbc:mysql://47.92.194.154:3306/hhzy_crm?characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 70
        test-on-borrow: true

