spring:
    datasource:
      url: jdbc:mysql://47.100.7.6:3306/hhzy?characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        initial-size: 3
        min-idle: 3
        max-active: 60
        test-on-borrow: true


